<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'; import { useRoute } from 'vue-router'; import { commerceApi } from '@/api/services'; import PageState from '@/shared/PageState.vue'; import { date,money,orderStatus } from '@/shared/format'
const route=useRoute(),loading=ref(true),error=ref(''),order=ref<any>({}),methods=ref<any[]>([]),selected=ref<any>(null),paying=ref(false);let timer:number|undefined
async function load(){loading.value=true;try{[order.value,methods.value]=await Promise.all([commerceApi.order(String(route.params.tradeNo)),commerceApi.paymentMethods().catch(()=>[])]);if(Number(order.value.status)===0)timer=window.setInterval(check,5000)}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function check(){const r=await commerceApi.checkPayment(String(route.params.tradeNo));const status=typeof r==='object' ? r?.status : r;if(status !== undefined && Number(status)!==0){order.value.status=Number(status);clearInterval(timer)}}
async function checkout(){if(!selected.value)return;paying.value=true;try{const result=await commerceApi.checkout({trade_no:route.params.tradeNo,method:selected.value.id});const payment=typeof result==='string'?result:result?.data ?? result;const url=typeof payment==='string'?payment:payment?.url || payment?.redirect_url;if(url)window.location.assign(url);else if(result?.type === -1) order.value.status=3; else throw new Error('支付网关未返回跳转地址')}catch(e:any){error.value=e.message}finally{paying.value=false}}
onMounted(load);onBeforeUnmount(()=>clearInterval(timer))
</script>
<template><PageState :loading="loading" :error="error" @retry="load"><div class="page-heading"><div><h1>订单详情</h1><p>#{{route.params.tradeNo}}</p></div><span class="status">{{orderStatus(order.status)}}</span></div><div class="detail-grid"><section class="panel detail-card"><h2>商品信息</h2><dl><div><dt>套餐</dt><dd>{{order.plan?.name||order.plan_name}}</dd></div><div><dt>周期</dt><dd>{{order.period}}</dd></div><div><dt>订单金额</dt><dd>{{money(order.total_amount??order.total)}}</dd></div><div><dt>创建时间</dt><dd>{{date(order.created_at,true)}}</dd></div></dl></section><section v-if="Number(order.status)===0" class="panel detail-card"><h2>选择支付方式</h2><button v-for="method in methods" :key="method.id" :class="['payment-method',{selected:selected?.id===method.id}]" @click="selected=method">{{method.name||method.payment}}</button><button class="button primary wide" :disabled="!selected||paying" @click="checkout">{{paying?'正在前往收银台':'立即支付'}}</button></section></div></PageState></template>
