<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { userApi } from '@/api/services'; import PageState from '@/shared/PageState.vue'; import { bytes, date } from '@/shared/format'
const loading=ref(true), error=ref(''), message=ref(''), data=ref<any>({}); async function load(){loading.value=true;error.value='';try{data.value=await userApi.subscribe()}catch(e:any){error.value=e.message}finally{loading.value=false}} onMounted(load)
const subscribeUrl=()=>data.value.subscribe_url || data.value.url || ''
async function copy(){const value=subscribeUrl();if(!value)return;try{await navigator.clipboard.writeText(value);message.value='订阅地址已复制'}catch{message.value='当前浏览器不支持自动复制，请手动复制订阅地址'}}
function openClient(client: string){const url=subscribeUrl();if(!url){message.value='当前没有可用订阅地址';return}const encoded=encodeURIComponent(url);const links:Record<string,string>={clash:`clash://install-config?url=${encoded}&name=${encodeURIComponent('Subscription')}`,shadowrocket:`shadowrocket://add/sub?url=${encoded}`,v2rayn:`v2rayn://install-config?url=${encoded}`};window.location.assign(links[client])}
async function reset(){try{data.value.subscribe_url=await userApi.resetSecurity();message.value='订阅地址已重置'}catch(e:any){error.value=e.message}}
</script>
<template><PageState :loading="loading" :error="error" @retry="load"><div class="page-heading"><div><h1>我的订阅</h1><p>查看用量，并将订阅导入常用客户端。</p></div></div><section class="detail-grid"><div class="panel detail-card"><h2>订阅信息</h2><dl><div><dt>上传流量</dt><dd>{{ bytes(data.u) }}</dd></div><div><dt>下载流量</dt><dd>{{ bytes(data.d) }}</dd></div><div><dt>总流量</dt><dd>{{ bytes(data.transfer_enable) }}</dd></div><div><dt>到期时间</dt><dd>{{ date(data.expired_at) }}</dd></div></dl></div><div class="panel detail-card"><h2>订阅地址</h2><p class="muted">请妥善保管订阅地址，泄漏后请及时重置。</p><div class="copy-row"><input readonly :value="subscribeUrl() || '暂无订阅地址'"/><button class="button primary" @click="copy">复制</button></div><div class="client-actions"><button class="button secondary" @click="openClient('clash')">Clash Verge</button><button class="button secondary" @click="openClient('shadowrocket')">Shadowrocket</button><button class="button secondary" @click="openClient('v2rayn')">v2rayN</button><button class="button secondary" @click="reset">重置地址</button></div><p v-if="message" class="form-message success">{{ message }}</p></div></section></PageState></template>
